name: Video Processing Pipeline

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes for new videos
  workflow_dispatch:  # Allow manual trigger

jobs:
  process-video:
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_DRIVE_CLIENT_ID: ${{ secrets.GOOGLE_DRIVE_CLIENT_ID }}
      GOOGLE_DRIVE_CLIENT_SECRET: ${{ secrets.GOOGLE_DRIVE_CLIENT_SECRET }}
      GOOGLE_DRIVE_REDIRECT_URI: ${{ secrets.GOOGLE_DRIVE_REDIRECT_URI }}
      GOOGLE_DRIVE_REFRESH_TOKEN: ${{ secrets.GOOGLE_DRIVE_REFRESH_TOKEN }}
      INPUT_FOLDER_ID: "1EurKyDd3HehsL70p5NWbHSlM0V7km6bh"
      OUTPUT_FOLDER_ID: "1VVj6pT4pWW9Nn18cQSh2XurQnGk1RHHF"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Load video preset
        id: load-preset
        run: |
          # Read the preset file and properly escape the JSON
          PRESET_CONTENT=$(cat video-preset.json | jq -c)
          echo "preset=${PRESET_CONTENT}" >> $GITHUB_ENV

      - name: Check for new videos and process
        run: |
          python - <<'EOF'
          import os
          import json
          from google.oauth2.credentials import Credentials
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaIoBaseDownload, MediaFileUpload
          import datetime
          import subprocess

          def get_google_drive_service():
              creds = Credentials(
                  None,
                  refresh_token=os.environ['GOOGLE_DRIVE_REFRESH_TOKEN'],
                  token_uri="https://oauth2.googleapis.com/token",
                  client_id=os.environ['GOOGLE_DRIVE_CLIENT_ID'],
                  client_secret=os.environ['GOOGLE_DRIVE_CLIENT_SECRET']
              )
              return build('drive', 'v3', credentials=creds)

          def run_ffmpeg_command(input_file, output_file, preset):
              # Construct FFmpeg command with proper codec names
              cmd = [
                  'ffmpeg', '-i', input_file,
                  '-c:v', 'libx264' if preset['videoCodec'] == 'h264' else preset['videoCodec'],
                  '-c:a', 'aac' if preset['audioCodec'] == 'aac' else preset['audioCodec'],
                  '-s', preset['resolution'],
                  '-b:v', f"{preset['bitrate']}k",
                  '-r', str(preset['fps']),
                  '-ac', str(preset['audioChannels']),
                  '-ar', str(preset['audioSampleRate']),
                  '-movflags', 'faststart',
                  '-y',  # Overwrite output file if it exists
                  output_file
              ]
              
              # Run FFmpeg command
              process = subprocess.run(cmd, capture_output=True, text=True)
              if process.returncode != 0:
                  raise Exception(f"FFmpeg error: {process.stderr}")

          def process_new_videos():
              service = get_google_drive_service()
              preset = json.loads(os.environ['preset'])
              
              # Get list of files in input folder
              query = f"'{os.environ['INPUT_FOLDER_ID']}' in parents and mimeType contains 'video/' and not trashed"
              results = service.files().list(
                  q=query,
                  fields="files(id, name, createdTime)"
              ).execute()
              
              for file in results.get('files', []):
                  created_time = datetime.datetime.strptime(
                      file['createdTime'], '%Y-%m-%dT%H:%M:%S.%fZ'
                  )
                  
                  # Process only videos created in the last 10 minutes
                  if (datetime.datetime.utcnow() - created_time).total_seconds() <= 600:
                      print(f"Processing new video: {file['name']}")
                      
                      # Download video
                      request = service.files().get_media(fileId=file['id'])
                      with open('input_video.mp4', 'wb') as f:
                          downloader = MediaIoBaseDownload(f, request)
                          done = False
                          while not done:
                              _, done = downloader.next_chunk()
                      
                      # Process video using FFmpeg
                      try:
                          run_ffmpeg_command('input_video.mp4', 'processed_video.mp4', preset)
                          
                          # Create thumbnail
                          subprocess.run([
                              'ffmpeg', '-i', 'processed_video.mp4',
                              '-ss', '00:00:02', '-vframes', '1',
                              'thumbnail.jpg'
                          ], check=True)
                          
                          # Check file size and split if necessary
                          size_mb = os.path.getsize('processed_video.mp4') / (1024 * 1024)
                          if size_mb > 98:
                              subprocess.run([
                                  'ffmpeg', '-i', 'processed_video.mp4',
                                  '-c', 'copy', '-f', 'segment',
                                  '-segment_time', '600',
                                  '-reset_timestamps', '1',
                                  'part%d.mp4'
                              ], check=True)
                              
                              # Upload parts
                              for part in sorted([f for f in os.listdir('.') if f.startswith('part') and f.endswith('.mp4')]):
                                  media = MediaFileUpload(part, mimetype='video/mp4')
                                  file_metadata = {
                                      'name': f"processed_{file['name']}_{part}",
                                      'parents': [os.environ['OUTPUT_FOLDER_ID']]
                                  }
                                  service.files().create(body=file_metadata, media_body=media, fields='id').execute()
                          else:
                              # Upload single processed video
                              media = MediaFileUpload('processed_video.mp4', mimetype='video/mp4')
                              file_metadata = {
                                  'name': f"processed_{file['name']}",
                                  'parents': [os.environ['OUTPUT_FOLDER_ID']]
                              }
                              service.files().create(body=file_metadata, media_body=media, fields='id').execute()
                          
                          # Upload thumbnail
                          media = MediaFileUpload('thumbnail.jpg', mimetype='image/jpeg')
                          file_metadata = {
                              'name': f"thumbnail_{file['name']}.jpg",
                              'parents': [os.environ['OUTPUT_FOLDER_ID']]
                          }
                          service.files().create(body=file_metadata, media_body=media, fields='id').execute()
                          
                      except Exception as e:
                          print(f"Error processing video {file['name']}: {str(e)}")
                          continue
                          
                      finally:
                          # Cleanup
                          for f in ['input_video.mp4', 'processed_video.mp4', 'thumbnail.jpg']:
                              if os.path.exists(f):
                                  os.remove(f)
                          for f in [f for f in os.listdir('.') if f.startswith('part') and f.endswith('.mp4')]:
                              os.remove(f)

          if __name__ == '__main__':
              process_new_videos()
          EOF
